### PR TITLE
Update chat.html

### PR DESCRIPTION
**Pull request by AALEKH**
Made footer to appear to appear as is required to appear in other page......my default browser was firefox so checked in it ....would appreciate if u guys check it on safari and chrome .....appearence of lol in black is problem of javascript i verified it by blocing javascript in my browser working on that bug tooo....but still this might be some fixing..... :-)

### CODE REVIEW

**Comment by logan-r** [comment]
@AALEKH I just added you as a collaborator so you can commit directly to the repo.

**Comment by Graeme22** [comment]
when I run vilify now, it loads and then theres a new game button and when I click on it it does nothing.

**Comment by ferndot** [comment]
Its been doing that for a while for me.  Some browsers don't even load :(

**Comment by AALEKH** [comment]
@Logi0 Thnku buddy...:)

**Comment by logan-r** [comment]
@Graeme22, @Joshua-S The engine is being redone, so there is a lot of bugs.
@AALEKH You're welcome!

**Comment by Graeme22** [comment]
it used to not load for me, now it loads, but I cant get past the new game button...

**Pull request merged**
